---
version: "3"

services:
  db_service:
    image: rajesh177/pyapp:database-image
    deploy:
      replicas: 1
    ports:
      - "3306:3306"
    networks:
      - mynets

  auth_service:
    image: rajesh177/pyapp:auth-image
    deploy:
      replicas: 1
    ports:
      - "5001:5001"
    networks:
      - mynets

  books_service:
    image: rajesh177/pyapp:book-image
    deploy:
      replicas: 1
    ports:
      - "5002:5002"
    networks:
      - mynets

  borrow_service:
    image: rajesh177/pyapp:borrow-image
    deploy:
      replicas: 1
    ports:
      - "5003:5003"
    networks:
      - mynets

  frontend_service:
    image: rajesh177/pyapp:fe-image
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    networks:
      - mynets

networks:
  mynets:
    driver: overlay
