---
version: "3"

services:
  db_service:
    image: rajesh177/pyapp:db-image
    deploy:
      replicas: 1
    ports:
      - "3306:3306"
    networks:
      - mynet

  auth_service:
    image: rajesh177/pyapp:auth-image
    deploy:
      replicas: 1
    ports:
      - "5001:5001"
    networks:
      - mynet

  books_service:
    image: rajesh177/pyapp:book-image
    deploy:
      replicas: 1
    ports:
      - "5002:5002"
    networks:
      - mynet

  borrow_service:
    image: rajesh177/pyapp:borrow-image
    deploy:
      replicas: 1
    ports:
      - "5003:5003"
    networks:
      - mynet

  frontend_service:
    image: rajesh177/pyapp:fe-image
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    networks:
      - mynet

networks:
  mynet:
    driver: overlay
